### ISSUE TITLE
i18n: make the .pot file available

### ISSUE THREAD

**Issue by Mejans** [nlogozzo/NickvisionMoney#108]
Hello,
to make contribution easier would it be possible de make the .pot file available?
I tried with meson but the version was too old and I lost time trying only to have that precious file :(

**Comment by nlogozzo** [comment]
@zothma

**Comment by zothma** [comment]
Hey @Mejans!

The problem with adding the POT file to the repository is that it has to stay consistent everytime, so anyone bringing code to the app with some UI text change has to also update the POT file. And, this effort is quite enormous compared to the effort taken by future maintainers to just generate the file, so that's why we didn't choose in the end to add it.

Keep in mind too that if you have problems now with generating the PO file, you'll have problems later when updating your translation as it requires almost the same command... I'd love to help you however in solving your problem.

What commands did you try and what where the results and errors?

**Comment by nlogozzo** [comment]
You can continue the chat here if you'd like...just closing the issue

**Comment by eli-schwartz** [comment]
> The problem with adding the POT file to the repository is that it has to stay consistent everytime, so anyone bringing code to the app with some UI text change has to also update the POT file.

Different projects have different approaches to doing this. Some update the POT file on every commit, others only do so once per release, a week before a scheduled release, after declaring a "string freeze" for translation teams to work.

**Comment by gunchleoc** [comment]
You should be able to automate creating and updating the pot file in a GitHub action.

A weblate would also greatly help, especially for contributors to small languages whose time is at a premium - I'm trying (and failing) to keep around 50 projects up to date. The e-mail notifications about updates are already worth it, and weblate also allows automated QA checks for placeholders.

**Comment by zothma** [comment]
@BoFFire @eli-schwartz from what I've seen, Weblate needs to be self-hosted, which we can't do now. Correct me if I'm wrong obviously, I've never used this platform to be honest, I've just followed their [download page](https://weblate.org/en/download/).

For the moment, for you and @gunchleoc, I generated a POT file that you can use as a model, in this [ZIP file](https://github.com/nlogozzo/NickvisionMoney/files/10171277/org.nickvision.money.pot_files.zip). The best you can do to contribute to the translation is to create a pull request and follow the instructions in the [translation section of the README](https://github.com/nlogozzo/NickvisionMoney#translating).

If you have any _costless_ idea of implementing a better solution, please do share it, but please provide documentation to help us a bit (not just the name of the solution :) )

**Comment by eli-schwartz** [comment]
Weblate doesn't *need* to be self-hosted.

It's libre software, with a flagship instance running on https://hosted.weblate.org, which is:
- free/gratis for libre projects, upon request
- SaaS starting at €19 / month (€99 / €299 if you want as many source strings or languages, respectively, as the free-for-libre-software offering)

So, since NickvisionMoney qualifies for the gratis plan for libre software, you could sign up for https://hosted.weblate.org, and have them take care of everything for you without paying a penny.

See, instead of their download page, their hosting page: https://weblate.org/en/hosting/


> **Weblate proudly supports libre projects**
> 
> If you feel like being supported by Weblate will help you, [set up your libre project](https://hosted.weblate.org/hosting/) and get the **Libre plan** gratis. It has the same limits as the **Advanced plan**, but only for public projects.

**Comment by zothma** [comment]
[https://hosted.weblate.org/hosting/](https://hosted.weblate.org/hosting/)
> **Please check in advance whether your project is eligible for gratis project hosting on this site.**
> [...]
> The project has had active development for at least three months.

Money has been started in January, but it has really been developed since mid-October. For this reason, the project may not be accepted yet. This is however something to keep in mind for later. I guess we'll be sticking to PRs for the moment.
