### ISSUE TITLE
Restrict file system access

### ISSUE THREAD

**Issue by vanillajonathan** [nlogozzo/NickvisionMoney#121]
Currently Money have read/write access to then user's entire home directory, this leads GNOME Software to flag it as "unsafe".

![image](https://user-images.githubusercontent.com/10222521/205944708-d7297dc4-5b16-4270-b711-8f2e4fed171c.png)

Flatpak have the concept of "Portals" which GTK implements:
https://docs.flatpak.org/en/latest/portals.html#portal-support-in-gtk

This grants the application access to files picked from the GTK file picker dialogs, so I think that Money doesn't really need `"--filesystem=home"`. An alternative would be to scope it to something like the Documents subdirectory, so it doesn't have access to all the files in the user's home directory.

https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html#filesystem-permissions
Example: `"--filesystem=xdg-documents"`.

**Comment by nlogozzo** [comment]
Permission access has always been a problem with C++ libraries. Although permission is granted from the portal on flatpak, C++ libraries (such as sqlite) still give me permission access denied when trying to open a file provided by the path from the portal. Hence why permission access is set to home. See #107 . Even though the user created the file from the portal and opened it. The app still couldn't access the file. Now, this occurred on a NAS, but the same issue happens if home access is removed and a user tries to create a file in the home directory.
So for now, permissions will stay as they are.

**Comment by fsobolev** [comment]
I was thinking about this problem today, and I have one solution. I first rejected it because it's a big change, but since we're rewriting the app, maybe you will accept this, @nlogozzo. But this is a **HUGE** UX change IMO.
There's the CSV export option. And it's not like *.nmoney files can be used somewhere else really. So what's reason why we let the user choose where to store these files? Except for syncing purposes ofc.
So why not to store files in the app's data folder (`~/.var/app/ID/data` for flatpak or `~/.local/share/app`)? This way we will not need any filesystem access. We can also easily list all accounts on start screen (and we'll have to - because there will not be "Open" button), sorted in the order of last used.
And for syncing, well, the user will not have the ability to place an account file anywhere, but all accounts will be in one place, inside home folder (yes, deep inside, but we can provide some hints in the app how to find the folder), so I don't think it would be much of a problem to configure syncing app to grab files from here. Or a systemd service to copy files from account folder to somewhere else can be easily written (I can do this if needed).

**Comment by vanillajonathan** [comment]
@nlogozzo Well it could be changed from `"--filesystem=home"` to `"--filesystem=xdg-documents"` that way the application would have access to a more limited scope. That should increase safety and trust. perhaps that would eliminate the "Money is unsafe" warning in GNOME Software.

@fsobolev I think a systemd service sounds rather undesirable.

**Comment by JoseBritto** [comment]
> And for syncing, well, the user will not have the ability to place an account file anywhere, but all accounts will be in one place, inside home folder (yes, deep inside, but we can provide some hints in the app how to find the folder), so I don't think it would be much of a problem to configure syncing app to grab files from here. Or a systemd service to copy files from account folder to somewhere else can be easily written (I can do this if needed).

This could be solved by providing a backup location option where if set the app could copy the nmoney file to the destination. A warning about lacking permissions could be provided here and the user can manually add the required permission using flatseal.

**Comment by nlogozzo** [comment]
If we're going to go to all this trouble for a systemd service or a backup location the app will still need permission to the home directory to be able to be backed up anywhere. Which at that point we might as well leave it the way it is.

**Comment by JoseBritto** [comment]
> If we're going to go to all this trouble for a systemd service or a backup location the app will still need permission to the home directory to be able to be backed up anywhere. Which at that point we might as well leave it the way it is.

My point was that backing up these files aren't something everyone would do and for the people who would want to do it, it wouldn't be too hard for them to figure out how to give access to the home directory using something like flatseal. Alternatively we could provide a button for the user to view the folder where the files are stored and from there they could use their own backup solutions like @fsobolev mentioned.
