### ISSUE TITLE
Translations gone

### ISSUE THREAD

**Issue by Mejans** [nlogozzo/NickvisionMoney#167]
Hello,
last month I made a contribution via a translation.
Today the translation is no longer in the git.
I see XML style files but I cannot use this with Poedit. Also, the time I took to translate is just lost now, I do not appreciate this reward =/

**Comment by Krindog7337** [comment]
looks like all the .po files is gone because it use .resx file for this project now?

**Comment by nlogozzo** [comment]
Hi! As @Krindog7337 the project now uses `.resx` files instead of `.po` files since the application is being rewritten in C#.

You can find out more information about creating `.resx` translation files via the [README](https://github.com/nlogozzo/NickvisionMoney#translating). `.resx` files are simple `.xml` files so you should be able to edit them with any editor.

Please see the following notes from the beta releases of the C# version:

From [V2023.1.0-beta1](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta1):
> Since we are now using C# and .NET 7, we have switched from `po` translation files to `resx` files. Providing a `resx` translation file will translate the app for both the WinUI and GNOME in one file. 
Please visit the [shared resources folder](https://github.com/nlogozzo/NickvisionMoney/tree/main/NickvisionMoney.Shared/Resources) to provide your translation. You will see a `Strings.ru.resx` file which is the Russian translation of the `Strings.resx` that you can use as a guide.
Visit the [README](https://github.com/nlogozzo/NickvisionMoney/blob/main/README.md#translating) file for more information.

From [V2023.1.0-beta2](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta2):
> The `Strings.resx` file is constantly being updated as the development of V2023.1.0 moves along. Although you can update your language's `resx` file as development moves along, we advise translators to wait until the release candidate version of V2023.1.0, which will give translators a period of 2/3 days to update their language file for the final release. Of course, if your language does not yet have a `resx` file, feel free to open a PR to add your language at any time!

**Comment by nlogozzo** [comment]
CC other translators:
@milotype @Vistaus @zothma @heymisphere @bordam @martin-desktops

**Comment by fsobolev** [comment]
In case somebody wants to copy-paste translated strings from old PO files, [here](https://github.com/fsobolev/NickvisionMoney/tree/cpp) is a backup of C++ version of the app. But it's not enough, because there are new strings, and there will be more when a release candidate for the next version will be published, so you might want to wait for it.

**Comment by bordam** [comment]
Yeah unfortunately I was home a very limited amount of time during this holiday and wasn’t able to update the translation… sorry!

**Comment by Vistaus** [comment]
@nlogozzo 

> Remember translations need to be constantly maintained and updated. It's never a one and done job.

Spot on. 👍🏻 

I'll update the translation ASAP. 2 questions though:

1. Are there any good tools to translate .resx files like there are for po files?
2. Just out of curiosity, why did you decide to switch?

**Comment by nlogozzo** [comment]
> Yeah unfortunately I was home a very limited amount of time during this holiday and wasn’t able to update the translation… sorry!

@bordam No worries. Take your time. We are still probably about a week away from a stable release. Buone feste :)

**Comment by nlogozzo** [comment]
> I'll update the translation ASAP. Quick questions though: are there any good tools to translate .resx files like there are for po files or do I need to use a text editor?

@Vistaus Not that I know of, but you should be able to edit `resx` files with any old text editor, since it's basically a `xml` file.

As previously mentioned, there are many new strings for new features and many new contexts created for some old strings, that require knowledge of the language/culture to translate properly (which would have been missed by any automatic conversion tool and hence why `po` files weren't converted to `resx` files automatically)

**Comment by milotype** [comment]
@nlogozzo 
Please provide existing translated .po files as .resx files in order to translate new strings.

**Comment by fsobolev** [comment]
> @Vistaus Not that I know of, but you should be able to edit `resx` files with any old text editor, since it's basically a `xml` file.

There are some addons for Visual Studio to show RESX files content in a grid and edit them, but I didn't test which of these addons works good since I don't use Visual Studio myself.

**Comment by Vistaus** [comment]
Thanks @nlogozzo.

And also thanks @fsobolev, but I'm using Linux.

**Comment by fsobolev** [comment]
> And also thanks @fsobolev, but I'm using Linux.

Sorry, I meant Visual Studio Code ofc, which is cross-platform.

**Comment by nlogozzo** [comment]
I'll try to find a good resx editor. If I can't,  might just make one myself 👀

**Comment by bordam** [comment]
Apparently Weblate supports Resx translations, so while we wait for implementing translations on hosted Weblate, translators could self-host it and translate from there

Don't know how complex it would be though, probably more than translating it from the text editor

**Comment by nlogozzo** [comment]
> Apparently Weblate supports Resx translations, so while we wait for implementing translations on hosted Weblate, translators could self-host it and translate from there

Yes I saw that it does have support for `resx`. My plan is to get translations on Weblate soon.

**Comment by nlogozzo** [comment]
Weblate hosting is here! https://hosted.weblate.org/engage/nickvision-money/

**Comment by Vistaus** [comment]
Yeahhhh, thank you so much, man! 🙂 🥳

**Comment by BoFFire** [comment]
Finally ! Weblate !
