### ISSUE TITLE
Flap size problem when set region to countries used rtl language 

### ISSUE THREAD

**Issue by iman-salmani** [nlogozzo/NickvisionMoney#211]
## spec:
fedora 37
gnome 43.2
installed by flatpak from flathub
app version 2022.11.1

## screenshot
![Screenshot from 2023-01-14 01-20-53](https://user-images.githubusercontent.com/32843050/212425820-f7ac2fae-c2a7-4c1d-a33c-d4356bba1a02.png)
![Screenshot from 2023-01-14 01-20-48](https://user-images.githubusercontent.com/32843050/212425845-56bc43b6-d6d2-4dce-8033-20cf7eedc4ea.png)
![Screenshot from 2023-01-14 01-22-44](https://user-images.githubusercontent.com/32843050/212425990-408f851c-0971-458a-89b0-4a8b7a57f419.png)

## How this happening
1. Gnome Settings
2. Region & Language
3. set formats to iran
> search for iran and select item with persian text

changing language dont have effect.
> i think because app dont have persian translation

terminal output have nothing to show 👍🏻
Thanks for your awesome application

**Comment by Krindog7337** [comment]
Looks like it's fine on the rewrite version 
![image](https://user-images.githubusercontent.com/92032579/212441892-9ccdc0f6-de95-4f13-aae7-bdd391d5010b.png)
![image](https://user-images.githubusercontent.com/92032579/212441897-ee609138-25fc-4908-befe-76f331fd2fdf.png)

here's another screenshot with arabic languange
![image](https://user-images.githubusercontent.com/92032579/212441917-6ff62a3e-501d-41dd-b579-edafef3e6864.png)
![image](https://user-images.githubusercontent.com/92032579/212441929-4513f733-aef3-46d6-9c61-674e061ec143.png)

**Comment by fsobolev** [comment]
With current master the situation is completely different:

![](https://i.imgur.com/CgzJmsY.png)

So there are 3 problems:
1. The application is still LTR
2. Calendar is not translated (and this is not due incomplete translation of the app, Gtk.Calendar should do it automatically)
3. Some strings are not displayed

The last one I will fix right now and it will go to the 2022.1.0, I understand why this happens, and other incomplete translations can also be affected by this.
For the rest... I need to investigate.

**Comment by fsobolev** [comment]
Pardon my ignorance, I noticed that on my screenshots the currency is wrong, because I set wrong locale...

@iman-salmani could you please type `locale` in terminal and copy the output here?

**Comment by iman-salmani** [comment]
in your screenshots first day of week is sunday with fa_ir locale its should be saturday.

### locale
`LANG=en_US.UTF-8`
`LC_CTYPE="en_US.UTF-8"`
`LC_NUMERIC=fa_IR.UTF-8`
`LC_TIME=fa_IR.UTF-8`
`LC_COLLATE="en_US.UTF-8"`
`LC_MONETARY=fa_IR.UTF-8`
`LC_MESSAGES="en_US.UTF-8"`
`LC_PAPER=fa_IR.UTF-8`
`LC_NAME="en_US.UTF-8"`
`LC_ADDRESS="en_US.UTF-8"`
`LC_TELEPHONE="en_US.UTF-8"`
`LC_MEASUREMENT=fa_IR.UTF-8`
`LC_IDENTIFICATION="en_US.UTF-8"`

### screenshot
![Screenshot from 2023-01-14 13-27-12](https://user-images.githubusercontent.com/32843050/212466430-5323ca94-8841-477d-be79-0d441d5a3a3a.png)

**Comment by fsobolev** [comment]
I just tried to run the current master version of the app with your setup and there was no issue with calendar as shown on your screenshot: `en_US` locale is used for everything. Unfortunately, also for currency and for the first day of week (Sunday).
The thing is, the current stable version (2022.11.1) was written in C++, but we rewrote the app in C#. C++ and C# handle mixed locales (when there are different locales for language and formats) a bit differently, and that's why the results are different. It doesn't mean C++ works better for mixed locales: I'm surprised it uses correct locales in your case, because when we investigated #153, C++ version didn't show any text at all, it failed to detect locale! C# at least always falls back to using language locale for everything.
I'm not sure if it's possible to make calendar use correct first day of week in case of mixed locales, I will investigate more. But for currency there's a workaround: you can use a custom one (not in stable version, but you can try 2023.1.0-rc1).
