### ISSUE TITLE
Add Import/Export from app

### ISSUE THREAD

**Issue by airon90** [nlogozzo/NickvisionMoney#22]
I use MoneyWallet from my Android phone and I'd like to have a backup on my laptop. Can you implement a fully Import/Export section?

**Comment by nlogozzo** [comment]
I think you have the wrong app. This is not MoneyWallet but is Nickvision Money.

**Comment by airon90** [comment]
No, I'd like to export my data from MoneyWallet and import them to your app

**Comment by nlogozzo** [comment]
Oh, i understand now sorry :)
How does MoneyWallet export data? Into a CSV file? Would you be able to attach a copy of an exported file for me to see how it is structured? Thanks!

**Comment by nlogozzo** [comment]
Unfortunately, if MoneyWallet does not export data as CSV, this feature will not be supported.

**Comment by carlocastoldi** [comment]
>Unfortunately, if MoneyWallet does not export data as CSV, this feature will not be supported.

But... MoneyWayllet can export data as CSV! Here is an example: [MoneyWallet_export_2022-11-26_00-44-21.csv](https://github.com/nlogozzo/NickvisionMoney/files/10095362/MoneyWallet_export_2022-11-26_00-44-21.csv)

Obviously, since its development dates back a few years, [MoneyWallet](https://github.com/AndreAle94/moneywallet) is a lot more complicated. This means that some things are not easily translatable in a CSV, and some information is lost. An example of things we cannot retriev from the CSV are:
- distinction between an expense and a transaction between wallets.
In the CSV a transaction is has its own category translated in the locale language (e.g. in italian: there is a "Trasferisci" category). A transaction is backedup as two different rows: one income and one expense. If they have a description, it is the same in both rows
- the list/tree of categories
- debits and credits
- events (and on which period they spanned over)
- recurring expenses/transactions
- budgets
- conversions between currencies

That said, having a way to sync between both apps would be very useful. Most of the time I add my expenses right after I have done it, so it comes handy to have a phone app for that. However it is slow, and if i have to ad a bunch of expenses it takes a while.
Having a way to use it in sync with NickvisionMoney would be a lovely addition!


I'd be also love to use NickvisionMoney on the phone, if there was GKT for android :P

**Comment by carlocastoldi** [comment]
However, MoneyWallet saves files in a JSON format.
This seems a more reasonable way to backup information about finances, if you ask me.
Surely, tho, since we  are talking about OSS we can try to open a bridge with the developer(s) of MoneyWallet and see if they're up for a ~collaboration

**Comment by fsobolev** [comment]
> I'd be also love to use NickvisionMoney on the phone, if there was GKT for android :P

The architecture of the app allows it to be ported to another widget toolkit, all the UI stuff is separated from the data processing, so I wouldn't be surprised if the app would be ported to Android. But it's not a task for the nearest future because first we need to make Money more mature in terms of features IMO.

**Comment by nlogozzo** [comment]
> > I'd be also love to use NickvisionMoney on the phone, if there was GKT for android :P
> 
> The architecture of the app allows it to be ported to another widget toolkit, all the UI stuff is separated from the data processing, so I wouldn't be surprised if the app would be ported to Android. But it's not a task for the nearest future because first we need to make Money more mature in terms of features IMO.

Yes we definitely need to work on implementing all the features into the desktop app before thinking about creating a campaign app.

**Comment by carlocastoldi** [comment]
>Yes we definitely need to work on implementing all the features into the desktop app before thinking about creating a campaign app.

that feels right. I get behind this plan.
Does this also mean that the import from MoneyWallet is postponed?
Also: is there a list of "all the features" to be implemented into the desktop app?

**Comment by nlogozzo** [comment]
> Does this also mean that the import from MoneyWallet is postponed?

For now, yes.

> Also: is there a list of "all the features" to be implemented into the desktop app?

You can view the list of [open issues](https://github.com/nlogozzo/NickvisionMoney/issues) for features we would like to implement :)

**Comment by carlocastoldi** [comment]
>You can view the list of [open issues](https://github.com/nlogozzo/NickvisionMoney/issues) for features we would like to implement :)

awesome! Thanks a lot ^^
