### ISSUE TITLE
Allow up to 3-character custom currency symbols

### ISSUE THREAD

**Issue by vanillajonathan** [nlogozzo/NickvisionMoney#232]
In USA you have $100, in Britain you have £100, but in Sweden you have 100 SEK, in Norway you have 100 NOK, in Denmark you have 100 DKK.

Some currencies have a symbol such as $ or £ or € but some currencies does not have any symbol.

**Comment by nlogozzo** [comment]
The custom currency symbol is allowed to have up to two characters or one emoji. 
In the meantime, you could use symbols like `SE` and `NO` for `SEK` and `NOK` respectively.

@fsobolev Should we extend the max character limit to 3 for custom currency symbol?

**Comment by vanillajonathan** [comment]
Also note that the national convention in some countries is to have the currency suffixed, not prefixed.

**Comment by nlogozzo** [comment]
The part of having currency suffixed or prefixed comes from your user locale.

For example, let's say you're in `en_US`. Currency symbols are displayed on the left: `$123.45`. Therefore, if you use a custom currency, let's say `SE` for the symbol. It will be displayed as `SE123.45` since that's the user's locale.

Same if you are in Sweden and change your symbol to `$`. The amount will be displayed as `123,45 $` because those are the settings of the system locale.

Remember, custom currency symbol/code have no regional information or anything like that. It's merely just changing the symbol and code used by Denaro. All formatting comes from your locale setting instead.

**Comment by vanillajonathan** [comment]
Maybe it uses `LANG` only?
I don't think it uses `LC_MONETARY`, `LC_TIME`, or `LC_NUMERIC`.

I have the language set to English (because I want the user interface in English), but I have another locale set for `LC_ADDRESS`, `LC_NAME`, `LC_MONETARY`, `LC_PAPER`, `LC_IDENTIFICATION`, `LC_TELEPHONE`, `LC_MEASUREMENT`, and `LC_TIME`.

**Comment by nlogozzo** [comment]
Yes, C# (as well as C++ when we had `Money`) uses `LANG` when generating CultureInfo. Hence the example scenario provided above.

**Comment by nlogozzo** [comment]
Use #233 to track the use of `LC_MONETARY` for number formats.

**Comment by fsobolev** [comment]
> I think the account setup dialog is confusing. For me it is not obvious what to write in the Currency Symbol and the Currency Code inputs.

https://en.wikipedia.org/wiki/Currency_symbol
https://en.wikipedia.org/wiki/ISO_4217

**Comment by vanillajonathan** [comment]
ISO 4217 is anything but obvious, you can't expect end-users to know about such standards.

The input could provide auto-completions to assist the user. The input could also have a placeholder or a textual description that explains the expected value.

**Comment by fsobolev** [comment]
> ISO 4217 is anything but obvious, you can't expect end-users to know about such standards.

We can't expect a user to know that currency codes are defined by ISO 4217 standard, but we can expect a user to understand a difference between currency code and currency symbol, because it's just a common properties of money, not something specific for Denaro. If somebody don't know how money works, it's not a Denaro bug.

**Comment by vanillajonathan** [comment]
Why can't it just provide a dropdown with a flag for each currency?

Example:
🇩🇰️ Danish krone
🇳🇴️ Norwegian krone
🇵🇱️ Polish złoty
🇸🇪️ Swedish krona
🇺🇦️ Ukrainian hryvnia

Then it would be much easier for the end-user.

**Comment by nlogozzo** [comment]
> Why can't it just provide a dropdown with a flag for each currency?
> 
> Example: 🇩🇰️ Danish krone 🇳🇴️ Norwegian krone 🇵🇱️ Polish złoty 🇸🇪️ Swedish krona 🇺🇦️ Ukrainian hryvnia
> 
> Then it would be much easier for the end-user.

Currency symbol != Country Flag

Currency symbol is the symbol of the currency...$, €, etc...
I don't understand what you are trying to do here. If you'd like you can add an emoji in the `Account Name` field to show up throughout the application.

**Comment by vanillajonathan** [comment]
100+ currencies doesn't sound so much, it doesn't should like it should be slow, I think it would render fast, plus you could use a dropdown with a built-in filter function or have a text input with autocompletion instead of a dropdown.

**Comment by fsobolev** [comment]
> 100+ currencies doesn't sound so much, it doesn't should like it should be slow, I think it would render fast, plus you could use a dropdown with a built-in filter function or have a text input with autocompletion instead of a dropdown.

If a user wants to use custom currency, they already know what currency it is, so dropdown with a full list of available currencies is useless. If a user doesn't understand difference between currency symbol and code, I'm sure a person who managed to install Denaro knows how to use google to get information about common terms - not Denaro-specific, not technical, not some terms that only economists use - **common** terms. But even without this knowledge, currency symbol can be anything, and it's not necessary to set custom currency code, it is optional, and it's made like this on purpose - a user might want to count dabloons, primogems from Genshin Impact, gold from World of Warcraft, or even candy wrappers - none of this are real-world currencies (well, candy wrappers are real, but not a currency) with established symbols and codes, and a user can use anything they want as symbol and as code - including not providing code at all if they decide they don't need it. Any hints or suggestions in UI will be insufficient or even more confusing, because a user might think the app expects something special, but no, any characters can be used. So it's better to not provide suggestions at all.

**Comment by vanillajonathan** [comment]
But this software will be used even by people who are not economists, so it would be good if the software was as simple as possible so that non-economists didn't have to resort to Google.

So if someone wants to use Denaro for _World of Warcraft_ gold or something with no defined currency symbol, then user is still required to set a Currency Symbol, maybe it should be optional too.
