### ISSUE TITLE
Suggest recent accounts when transferring money

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [nlogozzo/NickvisionMoney#244]
There is already a nice UI for account selection when opening the app.[^1] The same accounts should be listed as suggestions when transferring money. Currently, one needs to select a file using the file browser.[^2]

[^1]:  ![image](https://user-images.githubusercontent.com/15961647/213289637-38c19a68-40c1-4572-969c-4ab0718669ba.png)
[^2]: ![image](https://user-images.githubusercontent.com/15961647/213289964-3f6aaf97-6c0c-4bff-ba84-6a7317e69259.png)

**Comment by nlogozzo** [comment]
Progress from #250:

WinUI
![image](https://user-images.githubusercontent.com/17648453/213844449-d8df34e0-99f5-4934-900f-df0dc7a9473b.png)

GNOME
![image](https://user-images.githubusercontent.com/17648453/213844498-eb070a0a-c819-4101-a8b2-1d58f412971d.png)
*The wallet icon is missing in this screenshot due to me running on WSL. On a normal GNOME system, this will be the same icon you see from the `Recent Accounts` section of the MainWindow.*

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.0-beta1
