### ISSUE TITLE
Request to add a option to copy transaction

### ISSUE THREAD

**Issue by kaytise** [nlogozzo/NickvisionMoney#267]
When i record my transaction manually i need to write every option repeatedly. If there is an option to copy my previous transaction with it's selection it would be great. 
I use this application daily and it's been great. Thank you.

**Comment by fsobolev** [comment]
There are repeated transactions... But I guess it's not what you want, correct? You have transactions that you want to copy at arbitrary time without setting fixed repeat interval, did I understand it right?

**Comment by kaytise** [comment]
yeah

**Comment by fsobolev** [comment]
For now, it's not really convenient, but you can export your account as CSV, in this file (this is just plain text, can be edited in any text editor) you can add a copy of needed transaction with new ID, and then import this CSV file back.
But as I said, it's not convenient. I will think how to place copying function in the UI.

**Comment by nlogozzo** [comment]
@fsobolev Maybe we could add a duplicate button to transaction row and when the user clicks it, it will just create a new transaction with all that information. 

Of course if the user duplicates a source repeat transaction,  an entire set of new generated transactions would be created a well. 

Maybe we should warn the user when duplicating a source transaction?

**Comment by fsobolev** [comment]
@nlogozzo I don't think adding a new button to TransactionRow is good idea because:
1. I think it's not as common action as transaction editing or deleting, so ideally it shouldn't be on the same "level"
2. It will negatively impact the look of rows in compact mode

I have a different idea. We could place a button among TransactionDialog's buttons:

![](https://i.imgur.com/sgnROJH.png)

This button will only appear when editing existing transaction. After clicking on it, dialog gets reopened with all data copied, but with new ID, so it will be a dialog for a new transaction. At this point new transaction is not created yet - a user will need to click OK to actually add it, so this is an additional confirmation to not make a copy accidentally.

**Comment by nlogozzo** [comment]
Sounds good to me:)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.0-beta2
