### ISSUE TITLE
Support sync with Firefly III: online backend

### ISSUE THREAD

**Issue by xplosionmind** [nlogozzo/NickvisionMoney#352]
This app would be awesome and super useful, if it wasn't that it is limited to one device only. It would be great if it could follow the APIs of [Firefly III](https://firefly-iii.org) and become a **Firefly III client**.

**Comment by nlogozzo** [comment]
Becoming a Firefly III client isn't the best way to solve the issue of accessing your data on multiple accounts. This would defeat the purpose of Denaro since it would move all the transactions and reporting and all that to your Firefly III server and Denaro would just become a pretty UI that just calls a bunch of API things instead of doing any work itself...which is not what we want.

However, `.nmoney` files are compatible across devices and platforms (GNOME and WinUI)...so all you really need to do is just upload the file to a nextcloud server, google drive, onedrive, dropbox, mega, whatever syncing platform you use, and just open the `.nmoney` file from whatever device and all the data will be there. Denaro supports adding a password to an account which will encrypt the file, if you have any concerns of that.

As far as mobile, track with #277
