### ISSUE TITLE
GNOME - Use AdwTabOverview

### ISSUE THREAD

**Issue by nlogozzo** [nlogozzo/NickvisionMoney#396]

**Comment by nlogozzo** [comment]
On hold until gir.core supports libadwaita 1.3

**Comment by fsobolev** [comment]
We already discussed this. AdwTabOverview doesn't add much to the app's usability: Denaro is not designed to work with more than 3 accounts, it's the maximum that is remembered in recent accounts (we could increase the number tho, then it makes sense to use overview in case 5 accounts are opened for example, especially on mobile), and tabs previews will not differ much because the content of tabs is similar.

**Comment by nlogozzo** [comment]
ah true, forgot about that haha sorry :)
