### ISSUE TITLE
Remove scroll on "insert password" window

### ISSUE THREAD

**Issue by Krindog7337** [nlogozzo/NickvisionMoney#407]
Looks like it shouldn't have scroll abilities there, because there's nothing to show below the password input

[Screencast from 2023-03-29 14-34-48.webm](https://user-images.githubusercontent.com/92032579/228447766-3c97ddfa-bdcb-4810-9844-693ef019b56c.webm)

**Comment by fsobolev** [comment]
@nlogozzo @DaPigGuy I didn't find a way to disallow scrolling for `Adw.StatusPage`. Should we rework the dialog to not use this widget?

**Comment by nlogozzo** [comment]
Looks like it's scrolling because the account path is taking up two lines...could we just restrict it it to one? Or maybe just show "Filename.nmoney" instead of the whole path?

**Comment by fsobolev** [comment]
> Looks like it's scrolling because the account path is taking up two lines...

Yes, it's exactly the same issue we had with ScrollingWindow in AddDownloadDialog in Tube Converter: the dialog doesn't have a fixed size and isn't resizeable, so it tries to resize to place all children, but the content of the label is not known yet, so it's expected that level has 1 line, and when everything is rendered turns out the label has 2 lines, so it resizes its parent widgets up to ScrollingWindow that simply adds scrolling.

> could we just restrict it it to one? Or maybe just show "Filename.nmoney" instead of the whole path?

We can't restrict it because just like with ScrolledWindow there's not way to easily access the label in StatusPage. The filename itself can be long enough to not fit 1 line (especially on mobile). So I think the best option would be to change blp to achieve the same (or similar) result without using StatusPage and ScrolledWindow, so the label will resize the dialog if needed.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.4.0-rc1
