### ISSUE TITLE
CSV import into non-empty account

### ISSUE THREAD

**Issue by fsobolev** [nlogozzo/NickvisionMoney#41]
Import doesn't affect transactions with the same ID in both files, such transactions are neither imported as new transactions nor overwritten. I think it would be better if CSV file's transactions ID will be increased by the number of transactions in the account file, so everything will be imported anyway.

Tested both with master and #39

**Comment by nlogozzo** [comment]
@zothma Could you maybe make it where whenever we make a new transaction to add from CSV, just get the id from `Account::getNextAvailableTransactionId()` instead of the actual ID in the CSV row?

**Comment by zothma** [comment]
There is indeed quite a lot of work to do on CSV imports and exports.

> @zothma Could you maybe make it where whenever we make a new transaction to add from CSV, just get the id from `Account::getNextAvailableTransactionId()` instead of the actual ID in the CSV row?

Does that mean that you prefer this than overwriting existing transactions, as you told me a few days ago? If so, the id column becomes useless in the CSV and can be removed.

The same question also goes for groups: if two groups have the same ID, should it change the existing group by updating his name and his description, or create a new one? Creating a new one may also allow creation of duplicate groups, which would have to be handled...

With all that said, I do think that this is way beyond the scope of #39, which can be merged. A new PR seems more appropriate, as this issue is completely different from the issue solved in #39

**Comment by fsobolev** [comment]
> Does that mean that you prefer this than overwriting existing transactions, as you told me a few days ago? If so, the id column becomes useless in the CSV and can be removed.
>
> The same question also goes for groups: if two groups have the same ID, should it change the existing group by updating its name and description, or create a new one? Creating a new one may also allow creation of duplicate groups, which would have to be handled...

In my opinion both transactions and groups should be added, not overwritten. Because no matter what a user expects this behavior is not destructive. Overwriting basically destroys the data without any possibility to restore.

**Comment by nlogozzo** [comment]
On further thought, I think it's best to leave it as it is. 


Assume this scenario (with #39 since it has been merged)
A user creates an account and adds some groups and transactions:
![image](https://user-images.githubusercontent.com/17648453/201933640-3bd7bfb8-0f0c-42df-9227-3070a1f15798.png)
A user then decides to bulk-add some transactions from CSV. 
At first they export the account as CSV and get this file generated:
```csv
ID,Date,Description,Type,RepeatInterval,Amount,Group,GroupName,GroupDescription
1,2022-11-15,Pay Day,0,0,200,2,Bills,Stuff to pay
2,2022-11-15,Pay Day,0,0,200,1,Food,Restaurants and groceries
3,2022-11-15,Stop n Shop,1,0,105.74,1,Food,Restaurants and groceries
4,2022-11-15,November Phone Bill,1,0,65.26,2,Bills,Stuff to pay
```
The user then adds new transactions and groups and the CSV file becomes:
```csv
ID,Date,Description,Type,RepeatInterval,Amount,Group,GroupName,GroupDescription
1,2022-11-15,Pay Day,0,0,200,2,Bills,Stuff to pay
2,2022-11-15,Pay Day,0,0,200,1,Food,Restaurants and groceries
3,2022-11-15,Stop n Shop,1,0,105.74,1,Food,Restaurants and groceries
4,2022-11-15,November Phone Bill,1,0,65.26,2,Bills,Stuff to pay
5,2022-11-15,Pay Day,0,0,100,3,Travel,Gas and vacation
6,2022-11-15,Gas,1,0,32.00,3,Travel,Gas and vacation
```
This user then reimports the CSV file to add these new changes:
![image](https://user-images.githubusercontent.com/17648453/201934270-5c936fc6-9dbe-4485-9842-3422ae9b258d.png)
And everything is as expected.

If we were to implement the proposed changes of not caring about the ID of the transactions and groups from the CSV and just import everything, there would be duplicate transactions and groups everywhere for the user to cleanup. This is way the proper ID checks are in place as they are now.

**Comment by fsobolev** [comment]
Well, to be honest I didn't imagine more or less realistic scenario how a user might use CSV import/export feature. But you gave an example and now I understand why it works like this. Sorry for wasting your time, I will close the issue.
