### ISSUE TITLE
Maintain a separate repository for translations and append it into project using git submodule

### ISSUE THREAD

**Issue by heymisphere** [nlogozzo/NickvisionMoney#56]
Translations are being handled into the main repository, which makes commit history full of 'update transslation <>' commits. Can we maintain them into separate repository, which is appended into project repository using git submodule. The file structure would be accessible the same as it does correctly on Github and code history and translation history would be kept separate. For example:
[https://github.com/dialect-app/dialect](https://github.com/dialect-app/dialect) has submodule [https://github.com/dialect-app/po/tree/d7abf9dc4d2b6e153e6afeb2f1e6421fb94ce8f4](https://github.com/dialect-app/po/tree/d7abf9dc4d2b6e153e6afeb2f1e6421fb94ce8f4)

**Comment by nlogozzo** [comment]
Thanks for the suggestion, however I will not be separating translations into separate repositories. It works for Dialect because they have their own organization just for that app and can separate it like that. I manage a bunch of applications and creating separate translation repositories for each would get out of hand. Plus, majority of applications I've seen keep in within the same repo. Dialect is the first app i've ever seen that keeps it separate.

**Comment by fsobolev** [comment]
If a lot of "update translation" commits in history is considered a problem, then we could regenerate `.po` files and ask translators to update them only before stable releases. What do you think? @nlogozzo @heymisphere

**Comment by nlogozzo** [comment]
We could just ask translators to update before stable releases. However, I don't see this ask a problem to begin with.
