### ISSUE TITLE
Use Correct Prefix For Mimetype

### ISSUE THREAD

**Issue by heymisphere** [nlogozzo/NickvisionMoney#64]
The build fails, due to the newly added mimetype thing. When I replaced 'update-mime-database', '/app/share/mime', skip_if_destdir: true with just 'update-mime-database' in last line, the build happened successfully.

**Comment by nlogozzo** [comment]
When i change the line to just `update-mime-database` my build fails, since i'm using GNOME builder and it uses it as a flatpak.

Flatpak prefixes their app with `/app` whereas regular installed applications prefixes their app with `/usr`. Therefore i need to find a way to make the path of `update-mime-database` to be `PREFIX/share/mime`

**Comment by fsobolev** [comment]
> Flatpak prefixes their app with `/app` whereas regular installed applications prefixes their app with `/usr`. Therefore i need to find a way to make the path of `update-mime-database` to be `PREFIX/share/mime`

Maybe this will work?

```
meson.add_install_script('update-mime-database', join_paths(get_option('prefix'), get_option('datadir'), 'mime'), skip_if_destdir: true)
```

**Comment by nlogozzo** [comment]
That'll do it!

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/commit/8dfb733a07017d966f04f9b5461fe7c82dae1eb2

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.1-beta1
